name: .NET Release NuGet Package

on: 
    release:
        types:
            - published

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100 # SDK Version to use.
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: 'latest'
    - name: Restore packages
      run: nuget restore src\UPS.sln
    - name: .NET Build
      run: dotnet build src\UPS.sln --configuration Release
    - name: Create the package
      run: dotnet publish --configuration Release src\UPS\UPS.csproj
    - name: Publish to NuGet
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src\UPS\UPS.csproj
        VERSION_REGEX: '^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$'
        TAG_FORMAT: '*'
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

